"""
bo_tanimoto_morgan.py

Bayesian Optimisation using a TanimotoGP surrogate on the Morgan fingerprint
datasets generated by src/data/morgan_rf_dataset_generation.py.

The Tanimoto kernel is the natural choice for binary fingerprint inputs because
it measures molecular similarity in the same way as the standard Tanimoto
(Jaccard) coefficient, which is the field-standard metric for fingerprint
comparison. Using a Matérn or RBF kernel here would treat bits as continuous
features, which they aren't.

Experiment settings (kept consistent across all BO runs for fair comparison):
    - Surrogate       : SingleTaskGP with ScaleKernel(TanimotoKernel)
    - Acquisition fn  : LogExpectedImprovement
    - Initialisation  : hard-init -- 12 molecules drawn from the bottom 90th
                        percentile to avoid starting near the optimum
    - Budget          : 115 evaluations total (12 init + 103 BO steps)
    - Seeds           : 100-109 (10 independent replicates)
    - Threshold (TTF) : 1.30 V vs. SHE

Inputs:  Dataset/RF_importance_threshold/ (from morgan_rf_dataset_generation.py)
Outputs: Dataset/BO_TanimotoGP_MorganRF/

Usage:
    python src/models/bo_tanimoto_morgan.py
    # For a quick test, set SEEDS = [100] in the CONFIG section below
"""

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import torch
import gpytorch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_mll
from botorch.acquisition.analytic import LogExpectedImprovement
from botorch.utils.transforms import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_DIR     = Path(__file__).resolve().parents[2] / "data"
RF_DIR       = BASE_DIR / "RF_importance_threshold"
OUT_ROOT     = BASE_DIR / "BO_TanimotoGP_MorganRF"

TARGET_GLOB  = "Ritsuki_Morgan_RF_importancePercentile_*_withE0.csv"
TARGET_COL   = "E0_vs_SHE_V"
SID_COL      = "structure_id"
EXCLUDE      = {TARGET_COL, SID_COL, "Backbone", "Class", "Functional Group",
                "oxidised_smiles", "reduced_smiles"}

SEEDS        = list(range(100, 110))
N_INIT       = 12
TOTAL_BUDGET = 115
ELITE_Q      = 0.90   # hard-init: sample from below this percentile
THRESH       = 1.30   # V vs. SHE -- defines a "hit" for TTF
GP_MAXITER   = 50
SENTINEL     = -5.0
DEVICE       = "cpu"
DTYPE        = torch.double

COLORS = {"bo": "#1f77b4", "random": "#d62728"}


# ---------------------------------------------------------------------------
# Tanimoto kernel
#
# I'm defining this inline because BoTorch doesn't ship one out of the box.
# The formula is the standard Tanimoto similarity for real-valued vectors:
#   k(x, x') = <x, x'> / (||x||^2 + ||x'||^2 - <x, x'>)
# For binary vectors this reduces exactly to the Jaccard index.
# We clamp to [0, 1] to prevent floating-point drift from producing tiny
# negative values, which would break the GP's positive-definiteness.
# ---------------------------------------------------------------------------
class TanimotoKernel(gpytorch.kernels.Kernel):
    is_stationary = False

    def __init__(self, eps: float = 1e-6, **kwargs):
        super().__init__(**kwargs)
        self.eps = eps

    def forward(self, x1, x2, diag=False, **params):
        if diag:
            return torch.ones(x1.shape[-2], device=x1.device, dtype=x1.dtype)
        x1x2  = x1 @ x2.transpose(-1, -2)
        x1_sq = (x1 * x1).sum(dim=-1, keepdim=True)
        x2_sq = (x2 * x2).sum(dim=-1, keepdim=True).transpose(-1, -2)
        K = x1x2 / (x1_sq + x2_sq - x1x2 + self.eps)
        return K.clamp(0.0, 1.0)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
def ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)


def best_so_far(y: np.ndarray) -> np.ndarray:
    """Running maximum of y, i.e. best value found up to each step."""
    return np.maximum.accumulate(y)


def time_to_threshold(curve: np.ndarray, thresh: float):
    """Return the iteration index (1-based) when best_so_far first hits thresh."""
    idx = np.where(curve >= thresh)[0]
    return int(idx[0] + 1) if len(idx) else np.nan


def build_tanimoto_gp(X_train: torch.Tensor, y_train: torch.Tensor):
    """
    Fit a SingleTaskGP with the custom Tanimoto kernel.
    Note: X must NOT be standardised -- TanimotoKernel needs raw binary bits.
    The y values get standardised internally via BoTorch's standardize().
    """
    y_std = standardize(y_train)
    covar = gpytorch.kernels.ScaleKernel(TanimotoKernel())
    model = SingleTaskGP(X_train, y_std, covar_module=covar)
    mll   = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_mll(mll, options={"maxiter": GP_MAXITER})
    return model


def run_bo_loop(X_t: torch.Tensor,
                y_t: torch.Tensor,
                y:   np.ndarray,
                init_idx: list,
                n_iter: int):
    """
    Main BO loop. At each step:
      1. Fit the TanimotoGP on all observed points so far.
      2. Evaluate LogEI on the remaining (unobserved) pool.
      3. Pick the candidate with highest acquisition value and observe it.

    Returns the best-so-far curve and the array of observed y values.
    X is not standardised (required by TanimotoKernel).
    """
    remaining  = [i for i in range(len(y)) if i not in set(init_idx)]
    X_obs      = X_t[init_idx]
    y_obs      = y_t[init_idx]
    y_chosen   = y[init_idx].tolist()
    best_curve = best_so_far(np.array(y_chosen)).astype(float)

    for _ in range(n_iter):
        model  = build_tanimoto_gp(X_obs, y_obs)
        best_f = float(standardize(y_obs).max().item())
        acq    = LogExpectedImprovement(model=model, best_f=best_f)

        X_pool = X_t[remaining]
        with torch.no_grad():
            vals = acq(X_pool.unsqueeze(1)).squeeze(-1)

        pick_pos = int(torch.argmax(vals).item())
        nxt      = remaining[pick_pos]

        y_chosen.append(float(y_t[nxt].item()))
        X_obs    = torch.cat([X_obs, X_t[nxt].view(1, -1)], dim=0)
        y_obs    = torch.cat([y_obs, y_t[nxt].view(1, 1)],  dim=0)
        remaining.pop(pick_pos)
        best_curve = np.append(best_curve, max(best_curve[-1], y_chosen[-1]))

    return best_curve, np.array(y_chosen)


def _shade(ax, x, m, s, color, label, lw=2, ls="-"):
    """Plot a mean line with a ±1 std shaded band."""
    ax.plot(x, m, color=color, linewidth=lw, linestyle=ls, label=label)
    if np.any(s > 0):
        ax.fill_between(x, m - s, m + s, color=color, alpha=0.15)


# ---------------------------------------------------------------------------
# Per-dataset experiment
# ---------------------------------------------------------------------------
def run_dataset(csv_path: Path):
    dataset_name = csv_path.stem
    out_dir = OUT_ROOT / dataset_name
    ensure_dir(out_dir)

    # Load and filter
    df   = pd.read_csv(csv_path)
    y_s  = pd.to_numeric(df[TARGET_COL], errors="coerce")
    mask = y_s.notna() & (y_s > SENTINEL)
    df   = df.loc[mask].copy().reset_index(drop=True)
    y    = df[TARGET_COL].astype(float).values
    N    = len(df)
    B    = min(TOTAL_BUDGET, N)
    n_iter = B - N_INIT

    # Pull out just the Morgan fingerprint columns
    feat_cols = [c for c in df.columns if c not in EXCLUDE]
    X_df = df[feat_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0)

    # Sanity check: TanimotoKernel needs non-negative inputs
    if (X_df.values < 0).any():
        raise ValueError(
            f"Negative feature values found in {csv_path.name}. "
            "This shouldn't happen for binary Morgan bits -- check the CSV."
        )

    X_raw = X_df.values.astype(float)
    X_t   = torch.tensor(X_raw, device=DEVICE, dtype=DTYPE)
    y_t   = torch.tensor(y,     device=DEVICE, dtype=DTYPE).unsqueeze(-1)

    # Hard-init pool: molecules in the bottom ELITE_Q of the target distribution
    elite_cut = float(np.quantile(y, ELITE_Q))
    hard_pool = np.where(y < elite_cut)[0]

    d = X_t.shape[1]
    print(f"\n{'='*60}")
    print(f"Dataset : {dataset_name}")
    print(f"  N={N}  d={d}  hard_pool={len(hard_pool)}")
    print(f"  Budget={B}  init={N_INIT}  BO_steps={n_iter}")

    all_best  = []
    all_ttf   = []
    all_final = []

    for seed in SEEDS:
        rng      = np.random.default_rng(seed)
        init_idx = rng.choice(hard_pool, size=N_INIT, replace=False).tolist()

        print(f"  [seed {seed}] TanimotoGP LogEI ...", end=" ", flush=True)
        curve, y_obs = run_bo_loop(X_t, y_t, y, init_idx, n_iter)
        ttf = time_to_threshold(curve, THRESH)
        print(f"TTF={ttf}  final={curve[-1]:.4f}")

        pd.DataFrame({
            "y_observed":  y_obs,
            "best_so_far": curve,
        }).to_csv(out_dir / f"BO_trace_seed{seed}.csv", index=False)

        all_best.append(curve)
        all_ttf.append(ttf)
        all_final.append(float(curve[-1]))

    # Summary statistics across seeds
    ttfs_valid = [t for t in all_ttf if t is not None and not np.isnan(t)]
    summary = pd.DataFrame([{
        "dataset":     dataset_name,
        "surrogate":   "TanimotoGP",
        "acquisition": "LogEI",
        "n_init":      N_INIT,
        "n_seeds":     len(SEEDS),
        "budget":      B,
        "d":           d,
        "ttf_median":  float(np.nanmedian(all_ttf)),
        "ttf_std":     float(np.nanstd(all_ttf)),
        "ttf_min":     float(min(ttfs_valid)) if ttfs_valid else np.nan,
        "ttf_max":     float(max(ttfs_valid)) if ttfs_valid else np.nan,
        "n_fail":      len(all_ttf) - len(ttfs_valid),
        "final_mean":  float(np.mean(all_final)),
        "ttfs_all":    str(all_ttf),
    }])
    summary.to_csv(out_dir / "summary.csv", index=False)

    med = float(np.nanmedian(all_ttf))
    std = float(np.nanstd(all_ttf))
    print(f"  TTF median={med:.1f}  std={std:.2f}  "
          f"fails={len(all_ttf)-len(ttfs_valid)}/{len(SEEDS)}")

    # Convergence figure
    x   = np.arange(1, B + 1)
    arr = np.array(all_best)
    m, s = arr.mean(axis=0), arr.std(axis=0)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    ax = axes[0]
    _shade(ax, x, m, s, COLORS["bo"], f"TanimotoGP LogEI ({len(SEEDS)} seeds)")
    ax.axhline(THRESH, color="orange", linestyle="--", linewidth=1.2,
               label=f"Threshold {THRESH} V")
    ax.axvline(N_INIT, color="k", linestyle=":", linewidth=0.9,
               label=f"Init (n={N_INIT})")
    ax.set_xlabel("Evaluations")
    ax.set_ylabel("Best-so-far E₀ (V vs. SHE)")
    ax.set_title(f"TanimotoGP convergence -- {dataset_name}  (d={d})")
    ax.legend(fontsize=8)
    ax.grid(True)

    ax = axes[1]
    bp = ax.boxplot([ttfs_valid], labels=["TanimotoGP"],
                    patch_artist=True, widths=0.4)
    bp["boxes"][0].set_facecolor(COLORS["bo"])
    bp["boxes"][0].set_alpha(0.6)
    jitter = np.random.default_rng(0).uniform(-0.08, 0.08, len(ttfs_valid))
    ax.scatter(np.ones(len(ttfs_valid)) + jitter, ttfs_valid,
               color=COLORS["bo"], s=30, zorder=5, alpha=0.8)
    ax.set_ylabel("TTF (first hit iteration)")
    ax.set_title(f"TTF distribution -- {dataset_name}")
    ax.grid(True, axis="y")

    fig.suptitle(
        f"TanimotoGP + LogEI + hard-init (n={N_INIT})\n"
        f"{dataset_name}  |  TTF median={med:.1f}  std={std:.2f}",
        fontsize=10,
    )
    plt.tight_layout()
    plt.savefig(out_dir / "fig_convergence_ttf.png", dpi=300, bbox_inches="tight")
    plt.close(fig)

    return summary


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    ensure_dir(OUT_ROOT)

    csv_files = sorted(RF_DIR.glob(TARGET_GLOB))
    if not csv_files:
        raise FileNotFoundError(
            f"No Morgan percentile CSVs found in:\n  {RF_DIR}\n"
            "Run src/data/morgan_rf_dataset_generation.py first."
        )

    print("TanimotoGP BO -- Morgan RF Importance Datasets")
    print(f"Files  : {[f.name for f in csv_files]}")
    print(f"Seeds  : {SEEDS}  (n={len(SEEDS)})")
    print(f"N_INIT : {N_INIT}  |  Budget : {TOTAL_BUDGET}  |  Thresh : {THRESH} V")
    print(f"Output : {OUT_ROOT}")

    all_summaries = []
    for csv_path in csv_files:
        s = run_dataset(csv_path)
        all_summaries.append(s)

    combined = pd.concat(all_summaries, ignore_index=True)
    combined.to_csv(OUT_ROOT / "summary_all.csv", index=False)

    print("\n" + "=" * 60)
    print("Done.")
    print(combined[["dataset", "d", "ttf_median", "ttf_std",
                     "n_fail", "final_mean"]].to_string(index=False))
    print(f"\nSummary -> {OUT_ROOT / 'summary_all.csv'}")


if __name__ == "__main__":
    main()
